from typing import Set


class StopWordManager:
    """Manages stop words for filtering common/low-value terms."""

    DEFAULT_STOP_WORDS: Set[str] = {
        'a',
        'about',
        'above',
        'after',
        'again',
        'against',
        'all',
        'am',
        'an',
        'and',
        'any',
        'are',
        'as',
        'at',
        'be',
        'because',
        'been',
        'before',
        'being',
        'below',
        'between',
        'both',
        'but',
        'by',
        'can',
        'could',
        'did',
        'do',
        'does',
        'doing',
        'down',
        'during',
        'each',
        'few',
        'for',
        'from',
        'further',
        'had',
        'has',
        'have',
        'having',
        'he',
        'her',
        'here',
        'hers',
        'herself',
        'him',
        'himself',
        'his',
        'how',
        'i',
        'if',
        'in',
        'into',
        'is',
        'it',
        'its',
        'itself',
        'just',
        'me',
        'might',
        'more',
        'most',
        'my',
        'myself',
        'no',
        'nor',
        'not',
        'of',
        'off',
        'on',
        'only',
        'or',
        'other',
        'our',
        'ours',
        'ourselves',
        'out',
        'over',
        'own',
        'same',
        'she',
        'should',
        'so',
        'some',
        'such',
        'than',
        'that',
        'the',
        'their',
        'theirs',
        'them',
        'themselves',
        'then',
        'there',
        'these',
        'they',
        'this',
        'those',
        'through',
        'to',
        'too',
        'under',
        'until',
        'up',
        'very',
        'was',
        'we',
        'were',
        'what',
        'when',
        'where',
        'which',
        'while',
        'who',
        'whom',
        'why',
        'will',
        'with',
        'you',
        'your',
        'yours',
        'yourself',
        'yourselves',
    }

    def __init__(self, stop_words: set[str] | None = None) -> None:
        self.stop_words = stop_words or self.DEFAULT_STOP_WORDS

    def is_stop_word(self, token: str) -> bool:
        """Check if a token is a stop word."""
        return token.lower() in self.stop_words

    def filter_stop_words(self, tokens: list[str]) -> list[str]:
        """Remove stop words from a list of tokens."""
        return [token for token in tokens if not self.is_stop_word(token)]
